### ISSUE TITLE
[windows][ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by dlwfeng** [leanflutter/window_manager#184]
my flutter version:

> Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 85684f9300 (3 weeks ago) • 2022-06-30 13:22:47 -0700
> Engine • revision 6ba2af10bb
> Tools • Dart 2.17.5 • DevTools 2.12.2

my pubspec.yaml

> window_manager: ^0.2.5

my main.dart

``` dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  WindowOptions windowOptions = const WindowOptions(
      size: Size(60, 900),
      center: true,
      backgroundColor: Colors.transparent,
      skipTaskbar: false,
      titleBarStyle: TitleBarStyle.hidden,
      title: 'todo');
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });
  runApp(const MyApp());
}
```

console:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'double'
#0      WindowManager.getBounds (package:window_manager/src/window_manager.dart:292:17)
<asynchronous suspension>
#1      WindowManager.getSize (package:window_manager/src/window_manager.dart:319:19)
<asynchronous suspension>
#2      WindowManager.setAlignment (package:window_manager/src/window_manager.dart:267:23)
<asynchronous suspension>
#3      WindowManager.waitUntilReadyToShow (package:window_manager/src/window_manager.dart:116:34)
<asynchronous suspension>
```

**Comment by lijy91** [comment]
You need to call windowManager.ensureInitialized() where main starts

```diff
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
+  await windowManager.ensureInitialized();
  
  WindowOptions windowOptions = const WindowOptions(
      size: Size(60, 900),
      center: true,
      backgroundColor: Colors.transparent,
      skipTaskbar: false,
      titleBarStyle: TitleBarStyle.hidden,
      title: 'todo');
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });
  runApp(const MyApp());
}
```
