### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by Vallevard** [leanflutter/window_manager#194]
Hello all,

I'm trying to install bundle of an app on raspberry/raspbian using flutter-pi .(giving some context).

When I execute the command to run the application in command line, I received this error:

`
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method ensureInitialized on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      WindowManager.ensureInitialized (package:window_manager/src/window_manager.dart:93:5)
<asynchronous suspension>
#2      main (package:totems/main.dart:25:5)
<asynchronous suspension>
`

Do you think is something about compatibility of the window manager with linux/raspbian?

Thanks

**Comment by ziobudda** [comment]
Have you resolved ?

**Comment by ziobudda** [comment]
And which one do you use ?

**Comment by yjt1216** [comment]
oh,NO

**Comment by lijy91** [comment]
Closing: flutter-pi is a third-party embedder and window_manager only ships implementations for the official Flutter desktop embedders (macOS, Windows, Linux/GTK). The MissingPluginException means there is no native side for this platform, which is expected there.
